### ISSUE TITLE
Add new phone numbers for Lagos State Police based on a tweet

### ISSUE THREAD

**Issue by Oluwasetemi** [mykeels/police-ng-emergency#2]
## Description

Lagos State has released new emergency phone numbers, unique to Command Control Rooms and what look like Local Government Areas.

[See Tweet](https://twitter.com/DrOlufunmilayo/status/1249261977404411905/photo/4).

## Task

- [ ] Add these Phone Numbers to the repo
- [ ] Add VCF files for each Division and Command Control Room to a `vcf/lagos` folder
- [ ] Update the lagos.vcf file with all these new phone numbers, and the divisions/commands they represent
- [ ] Update the gh-pages branch's index.html, so that users can download the phone contacts

## Screenshots

![image](https://user-images.githubusercontent.com/11996508/79245243-c2081280-7e6f-11ea-9fe3-0d1044072a04.png)

![image](https://user-images.githubusercontent.com/11996508/79245277-ce8c6b00-7e6f-11ea-8a40-dc164ca48f1b.png)

![image](https://user-images.githubusercontent.com/11996508/79245300-d64c0f80-7e6f-11ea-9aa2-98e70b020bae.png)

![image](https://user-images.githubusercontent.com/11996508/79245313-da782d00-7e6f-11ea-83d5-3497d89a7da5.png)

**Comment by mykeels** [comment]
@Oluwasetemi:

```
[Tweet link](https://twitter.com/mykeels/status/1250064675364048908?s=20)

Should I group the new phone number under a cities object and create a vcard for each new phone number
```

@mykeels:

Awesome, thanks!

Let me look at the code. I haven't seen it in a while.

**Comment by mykeels** [comment]
All the phone numbers in the tweet are for Lagos state police command, so it might be worth it to have an extra `lagos-emergency-contacts.json` file, and create the lagos.vcf file with it.

**Comment by lilpolymath** [comment]
Yeah, so I found a way to gather the phone numbers quickly. Using Cloud Vision API from Google.

**Comment by mykeels** [comment]
It might also be worth it to have an additional page for Lagos, have different VCF files per local government for the state, in one lagos folder, and one giant `lagos-vcf` file for everything.

**Comment by mykeels** [comment]
@lilpolymath could you share?

**Comment by lilpolymath** [comment]
Here is it: https://cloud.google.com/vision/docs/drag-and-drop Currently on it.

For the VCF: It would be easier if people could just search for their area and get whatever names/phone numbers that they need instead of having to download a large vcf. What if the person is on PC or something?

**Comment by lilpolymath** [comment]
And using a VCF means we assume everyone has worked with a vcf before.

**Comment by Oluwasetemi** [comment]
> All the phone numbers in the tweet are for Lagos state police command, so it might be worth it to have an extra `lagos-emergency-contacts.json` file, and create the lagos.vcf file with it.

Yes this is valid. I will follow this format

**Comment by lilpolymath** [comment]
What format are you using to make the work faster?

**Comment by lilpolymath** [comment]
I am using something like this

> {
  "Command Center": {
    "Control 1": "09010512285",
    "Control 2": "09105122863",
    "Control 3": "09010512287",
    "Control 4": "09010512288"
  },
  "Area Command A": {
    "Location": "Lion Building",
    "Command Center": "090105112962",
    "Districts": {
      "Victoria Island": "09010511297",
      "Dolphin Estate": "09010511298",
      "Ikoyi": "09010511299",
      "Onikan": "09010511300",
      "Adeniji-Adele": "09010511301"
    }
  }
}

**Comment by mykeels** [comment]
@lilpolymath we're working with this.

https://github.com/mykeels/police-ng-emergency/blob/master/emergency-contacts.json#L167-L173

It could be extended into something like

```json
{
  "state": "lagos",
  "phones": [
    "07055462708",
    "08035963919"
  ],
  "divisions": [
    {
      "name": "Command 1",
      "phone": "0801..."
    },
    {
      "name": "Command 2",
      "phone": "0801..."
    },
    {
      "name": "Victoria Island",
      "phone": "0801..."
    }
  ]
}
```

**Comment by Oluwasetemi** [comment]
![image](https://user-images.githubusercontent.com/10030028/79244028-4fe2fe00-7e6e-11ea-8de0-250bf56b3372.png)

**Comment by lilpolymath** [comment]
> @lilpolymath we're working with this.
> 
> https://github.com/mykeels/police-ng-emergency/blob/master/emergency-contacts.json#L167-L173
> 
> It could be extended into something like
> 
> ```json
> {
>   "state": "lagos",
>   "phones": [
>     "07055462708",
>     "08035963919"
>   ],
>   "divisions": [
>     {
>       "name": "Command 1",
>       "phone": "0801..."
>     },
>     {
>       "name": "Command 2",
>       "phone": "0801..."
>     },
>     {
>       "name": "Victoria Island",
>       "phone": "0801..."
>     }
>   ]
> }
> ```

Alright awesome.

**Comment by mykeels** [comment]
Oh, I just saw there are command control rooms. This is hard. 😂

**Comment by Oluwasetemi** [comment]
Since @lilpolymath is working on it I will drop it. Nice repo idea

**Comment by Oluwasetemi** [comment]
We could make the commands a key in the JSON too

**Comment by mykeels** [comment]
@lilpolymath @Oluwasetemi  perhaps, this?

```json
{
  "state": "lagos",
  "phones": [
    "07055462708",
    "08035963919"
  ],
  "divisions": [
    {
      "name": "Victoria Island",
      "phone": "0801..."
    }
  ],
  "commandControlRooms": [
    {
      "name": "Command 1",
      "phone": "0801..."
    },
    {
      "name": "Command 2",
      "phone": "0801..."
    }
  ]
}
```

**Comment by Oluwasetemi** [comment]
Yes
That is better.

**Comment by mykeels** [comment]
Thanks @Oluwasetemi for picking this up. 

@lilpolymath could you assign yourself to this issue?

**Comment by lilpolymath** [comment]
Alright.

**Comment by mykeels** [comment]
@lilpolymath You might want to take a look at the updated description above.

**Comment by Oluwasetemi** [comment]
Nice work @mykeels for the description above! Well detailed.

**Comment by lilpolymath** [comment]
Seen.

**Comment by lilpolymath** [comment]
This issue can be close yeah?

**Comment by mykeels** [comment]
Yep, thanks
